=== rtruxal/bing-website-finder/test/schemas/email_resp1.schema.json
{
   "definitions": {},
   "$schema": "http://json-schema.org/draft-07/schema#",
   "$id": "http://example.com/root.json",
   "type": "object",
   "title": "The Root Schema",
   "required": [
     "_type",
     "queryContext",
     "webPages",
     "rankingResponse"
   ],
   "properties": {
     "_type": {
       "$id": "#/properties/_type",
       "type": "string",
       "title": "The _type Schema",
       "default": "",
       "examples": [
         "SearchResponse"
       ],
       "pattern": "^(.*)$"
     },
     "queryContext": {
       "$id": "#/properties/queryContext",
       "type": "object",
       "title": "The Querycontext Schema",
       "required": [
         "originalQuery"
       ],
       "properties": {
         "originalQuery": {
           "$id": "#/properties/queryContext/properties/originalQuery",
           "type": "string",
           "title": "The Originalquery Schema",
           "default": "",
           "examples": [
             "+\"@cisco.com\""
           ],
           "pattern": "^(.*)$"
         }
       }
     },
     "webPages": {
       "$id": "#/properties/webPages",
       "type": "object",
       "title": "The Webpages Schema",
       "required": [
         "webSearchUrl",
         "totalEstimatedMatches",
         "value"
       ],
       "properties": {
         "webSearchUrl": {
           "$id": "#/properties/webPages/properties/webSearchUrl",
           "type": "string",
           "title": "The Websearchurl Schema",
           "default": "",
           "examples": [
             "https://www.bing.com/search?q=%2b%22%40cisco.com%22"
           ],
           "pattern": "^(.*)$"
         },
         "totalEstimatedMatches": {
           "$id": "#/properties/webPages/properties/totalEstimatedMatches",
           "type": "integer",
           "title": "The Totalestimatedmatches Schema",
           "default": 0,
           "examples": [
             721000
           ]
         },
         "value": {
           "$id": "#/properties/webPages/properties/value",
           "type": "array",
           "title": "The Value Schema",
           "items": {
             "$id": "#/properties/webPages/properties/value/items",
             "type": "object",
             "title": "The Items Schema",
             "required": [
               "id",
               "name",
               "url",
               "isFamilyFriendly",
               "displayUrl",
               "snippet",
               "language",
               "isNavigational"
             ],
             "properties": {
               "id": {
                 "$id": "#/properties/webPages/properties/value/items/properties/id",
                 "type": "string",
                 "title": "The Id Schema",
                 "default": "",
                 "examples": [
                   "https://api.cognitive.microsoft.com/api/v7/#WebPages.0"
                 ],
                 "pattern": "^(.*)$"
               },
               "name": {
                 "$id": "#/properties/webPages/properties/value/items/properties/name",
                 "type": "string",
                 "title": "The Name Schema",
                 "default": "",
                 "examples": [
                   "Cisco Learning Library"
                 ],
                 "pattern": "^(.*)$"
               },
               "url": {
                 "$id": "#/properties/webPages/properties/value/items/properties/url",
                 "type": "string",
                 "title": "The Url Schema",
                 "default": "",
                 "examples": [
                   "https://digital-learning.cisco.com/"
                 ],
                 "pattern": "^(.*)$"
               },
               "isFamilyFriendly": {
                 "$id": "#/properties/webPages/properties/value/items/properties/isFamilyFriendly",
                 "type": "boolean",
                 "title": "The Isfamilyfriendly Schema",
                 "default": false,
                 "examples": [
                   true
                 ]
               },
               "displayUrl": {
                 "$id": "#/properties/webPages/properties/value/items/properties/displayUrl",
                 "type": "string",
                 "title": "The Displayurl Schema",
                 "default": "",
                 "examples": [
                   "https://digital-learning.cisco.com"
                 ],
                 "pattern": "^(.*)$"
               },
               "snippet": {
                 "$id": "#/properties/webPages/properties/value/items/properties/snippet",
                 "type": "string",
                 "title": "The Snippet Schema",
                 "default": "",
                 "examples": [
                   "Welcome to the newly upgraded Cisco Learning Library, previously known as Cisco Technical Education. As part of this exciting new upgrade, we are moving to a simplified single sign on process using Email ID. Your Email ID is the same ID used for access to other Cisco sites such as Cisco.com. This means one of four things for you"
                 ],
                 "pattern": "^(.*)$"
               },
               "language": {
                 "$id": "#/properties/webPages/properties/value/items/properties/language",
                 "type": "string",
                 "title": "The Language Schema",
                 "default": "",
                 "examples": [
                   "en"
                 ],
                 "pattern": "^(.*)$"
               },
               "isNavigational": {
                 "$id": "#/properties/webPages/properties/value/items/properties/isNavigational",
                 "type": "boolean",
                 "title": "The Isnavigational Schema",
                 "default": false,
                 "examples": [
                   false
                 ]
               }
             }
           }
         }
       }
     },
     "rankingResponse": {
       "$id": "#/properties/rankingResponse",
       "type": "object",
       "title": "The Rankingresponse Schema",
       "required": [
         "mainline"
       ],
       "properties": {
         "mainline": {
           "$id": "#/properties/rankingResponse/properties/mainline",
           "type": "object",
           "title": "The Mainline Schema",
           "required": [
             "items"
           ],
           "properties": {
             "items": {
               "$id": "#/properties/rankingResponse/properties/mainline/properties/items",
               "type": "array",
               "title": "The Items Schema",
               "items": {
                 "$id": "#/properties/rankingResponse/properties/mainline/properties/items/items",
                 "type": "object",
                 "title": "The Items Schema",
                 "required": [
                   "answerType",
                   "resultIndex",
                   "value"
                 ],
                 "properties": {
                   "answerType": {
                     "$id": "#/properties/rankingResponse/properties/mainline/properties/items/items/properties/answerType",
                     "type": "string",
                     "title": "The Answertype Schema",
                     "default": "",
                     "examples": [
                       "WebPages"
                     ],
                     "pattern": "^(.*)$"
                   },
                   "resultIndex": {
                     "$id": "#/properties/rankingResponse/properties/mainline/properties/items/items/properties/resultIndex",
                     "type": "integer",
                     "title": "The Resultindex Schema",
                     "default": 0,
                     "examples": [
                       0
                     ]
                   },
                   "value": {
                     "$id": "#/properties/rankingResponse/properties/mainline/properties/items/items/properties/value",
                     "type": "object",
                     "title": "The Value Schema",
                     "required": [
                       "id"
                     ],
                     "properties": {
                       "id": {
                         "$id": "#/properties/rankingResponse/properties/mainline/properties/items/items/properties/value/properties/id",
                         "type": "string",
                         "title": "The Id Schema",
                         "default": "",
                         "examples": [
                           "https://api.cognitive.microsoft.com/api/v7/#WebPages.0"
                         ],
                         "pattern": "^(.*)$"
                       }
                     }
                   }
                 }
               }
             }
           }
         }
       }
     }
   }
 }

=== rtruxal/bing-website-finder/test/data/resp4.json
{
    "_type": "SearchResponse",
    "queryContext": {
        "originalQuery": "Timmothy Cruise",
        "alteredQuery": "timothy cruise",
        "alterationDisplayQuery": "timothy cruise",
        "alterationOverrideQuery": "+Timmothy Cruise",
        "adultIntent": false
    },
    "webPages": {
        "webSearchUrl": "https://www.bing.com/search?q=Timmothy+Cruise",
        "totalEstimatedMatches": 16600000,
        "value": [
            {
                "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.2",
                "name": "Timothy Cruise (J), 58 - Canton, MA | Background Report at ...",
                "url": "https://www.mylife.com/timothy-cruise/e151428700530",
                "isFamilyFriendly": true,
                "displayUrl": "https://www.mylife.com/timothy-cruise/e151428700530",
                "snippet": "Timothy Cruise is 58 years old and was born on 05/15/1960. Timothy's Reputation Score is 3.45. Timothy Cruise lives in Canton, MA; previous cities include Sharon MA, Buzzards Bay MA and Brockton MA. Sometimes Timothy goes by various nicknames including Timothy J Cruice, Timothy J Cruise, Timmothy Cruise, Tim Cruise and Timmothy J Cruise.",
                "language": "en",
                "isNavigational": false
            },
            {
                "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.4",
                "name": "Timothy Cruise - BeenVerified",
                "url": "https://www.beenverified.com/people/timothy-cruise/",
                "about": [
                    {
                        "name": "In The"
                    },
                    {
                        "name": "In The"
                    }
                ],
                "isFamilyFriendly": true,
                "displayUrl": "https://www.beenverified.com/people/timothy-cruise",
                "snippet": "BeenVerified > People Search > Timothy Cruise; Timothy Cruise in the US. We found 17 results for Timothy Cruise.Search public records for emails, phone numbers, addresses and more.",
                "dateLastCrawled": "2019-02-23T05:32:00.0000000Z",
                "language": "en",
                "isNavigational": false
            },
            {
                "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.5",
                "name": "Tom Cruise - Wikipedia",
                "url": "https://en.wikipedia.org/wiki/Tom_Cruise",
                "thumbnailUrl": "https://www.bing.com/th?id=OIP.oY9X3RNcRtK4A_b0tURvsAAAAA&pid=Api",
                "about": [
                    {
                        "name": "Tom Cruise"
                    },
                    {
                        "name": "Tom Cruise"
                    }
                ],
                "isFamilyFriendly": true,
                "displayUrl": "https://en.wikipedia.org/wiki/Tom_Cruise",
                "snippet": "Thomas Cruise (born Thomas Cruise Mapother IV on July 3, 1962) is an American actor and producer. He started his career at age 19, in the film Endless Love (1981), ...",
                "dateLastCrawled": "2019-03-01T07:14:00.0000000Z",
                "language": "en",
                "isNavigational": false
            },

            {
                "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.7",
                "name": "Timothy Cruise - whitepages.com",
                "url": "https://www.whitepages.com/name/Timothy-Cruise",
                "isFamilyFriendly": true,
                "displayUrl": "https://www.whitepages.com/name/Timothy-Cruise",
                "snippet": "View phone numbers, addresses, public records, background check reports and possible arrest records for Timothy Cruise. Whitepages people search is the most trusted directory. Sign up to gain access to mobile numbers, public records, and more.",
                "language": "en",
                "isNavigational": false
            },
            {
                "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.8",
                "name": "Timothy Levitch - Wikipedia",
                "url": "https://en.wikipedia.org/wiki/Timothy_%22Speed%22_Levitch",
                "about": [
                    {
                        "name": "Timothy Levitch"
                    },
                    {
                        "name": "Timothy Levitch"
                    }
                ],
                "isFamilyFriendly": true,
                "displayUrl": "https://en.wikipedia.org/wiki/Timothy_\"Speed\"_Levitch",
                "snippet": "Timothy \"Speed\" Levitch (/ ... Levitch's cult was spread beyond NYC when he became the subject of the 1998 documentary The Cruise. In 2000, Levitch was a citizen of the art project Quiet, We Live in Sane. In August 2012, Levitch premiered a new documentary video series on its own Hulu channel.",
                "snippetAttribution": {
                    "license": {
                        "name": "CC-BY-SA",
                        "url": "http://creativecommons.org/licenses/by-sa/3.0/"
                    },
                    "licenseNotice": "Text under CC-BY-SA license"
                },
                "dateLastCrawled": "2019-03-02T17:19:00.0000000Z",
                "language": "en",
                "isNavigational": false
            }
        ]
    },
    "rankingResponse": {
        "mainline": {
            "items": [
                {
                    "answerType": "WebPages",
                    "resultIndex": 0,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.0"
                    }
                },
                {
                    "answerType": "WebPages",
                    "resultIndex": 1,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.1"
                    }
                },
                {
                    "answerType": "WebPages",
                    "resultIndex": 2,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.2"
                    }
                },
                {
                    "answerType": "WebPages",
                    "resultIndex": 3,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.3"
                    }
                },
                {
                    "answerType": "WebPages",
                    "resultIndex": 4,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.4"
                    }
                },
                {
                    "answerType": "WebPages",
                    "resultIndex": 5,
                    "value": {
                        "id": "https://api.cognitive.microsoft.com/api/v7/#WebPages.5"
                    }
                }
            ]
        }
    }
}
